### ISSUE TITLE
Error on Synology

### ISSUE THREAD

**Issue by nerfdaderp** [Tweeticoats/stash-vr-companion#1]
Hi there. First off, this is amazing. I've been hoping for something to bring stash over to the VR realm since I became aware of it.  Thanks so much for your efforts.  

I'm trying to stand this up on Synology and I'm getting an Internal Server error when I attempt to connect in. I did have to update several of the ports but I don't think that is the issue. Maybe python version?

The only change I made to the recommended creation script was to update the 5000 ext port to 10002 as Synology uses 5000 for host access and stash to port 10000 as I have XBVR on 9999.

docker run -d  --name=stash-vr-companion --restart=unless-stopped -p 10002:5000 -e API_URL=http://192.168.1.199:10000/graphql ghcr.io/tweeticoats/stash-vr-companion:latest

Logging has it looping the below GET error (post boot logging - it's not cycling or anything).

 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.17.0.8:5000/ (Press CTRL+C to quit)
[2021-12-15 12:07:33,938] ERROR in app: Exception on /filter/Recent [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/app.py", line 659, in show_category
    filters=filter()
  File "/app/app.py", line 616, in filter
    flat_filter['filter'] = {"tags": {"value": [tags_cache['export_deovr']['id'],tags_cache['FLAT']['id']], "depth": 0, "modifier": "INCLUDES_ALL"}}
KeyError: 'FLAT'
172.17.0.1 - - [15/Dec/2021 12:07:33] "GET /filter/Recent HTTP/1.1" 500 -
[2021-12-15 12:07:37,974] ERROR in app: Exception on /filter/Recent [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/app.py", line 659, in show_category
    filters=filter()
  File "/app/app.py", line 616, in filter
    flat_filter['filter'] = {"tags": {"value": [tags_cache['export_deovr']['id'],tags_cache['FLAT']['id']], "depth": 0, "modifier": "INCLUDES_ALL"}}
KeyError: 'FLAT'
172.17.0.1 - - [15/Dec/2021 12:07:37] "GET /filter/Recent HTTP/1.1" 500 -
172.17.0.1 - - [15/Dec/2021 12:07:51] "GET / HTTP/1.1" 302 -
[2021-12-15 12:07:51,226] ERROR in app: Exception on /filter/Recent [GET]

**Comment by peterpannimmerland** [comment]
Hi,
i have a synology nas too. I have no problem.
I want to explain how I got it to work:

First logon via ssh to your nas, then download the container:
sudo docker pull ghcr.io/tweeticoats/stash-vr-companion:latest
after that you should see the container in your gui:
![image](https://user-images.githubusercontent.com/91016000/146336994-287b959b-a629-4ed0-a3c7-9d51a2e9e9d5.png)

My configuration to start:
![image](https://user-images.githubusercontent.com/91016000/146337175-cc15c9ac-d871-41fe-826c-53680ee65618.png)
![image](https://user-images.githubusercontent.com/91016000/146337237-6487b410-c1de-422d-9cf7-1f7088f1c38e.png)
![image](https://user-images.githubusercontent.com/91016000/146337515-452b29ad-1fe4-46cf-b300-654c83d7138c.png)
if you have an login to your stash you also need the API_Key Parameter:
API_KEY = 

Then it works 

Could you share your config?

regards

**Comment by nerfdaderp** [comment]
Sure, my config seems to be similar to yours. I also just redid it using
the method you provided as opposed to scripting in the variables as before,
Same error. Now I'm thinking it's a stash issue as when I try to access the
graphql page, I get the below error which would certainly make
stash-companion fail as well. Ah it's always something :)

[image: image.png]


[image: stashvrconfig.jpg]

**Comment by nerfdaderp** [comment]
And stash-side logging seems to be happy with graphql, at least I see
successful calls to the URL so maybe it's not that haha

**Comment by nerfdaderp** [comment]
The issue is fixed. I had a) assumed flat was not required as it mentioned default. b) when I did create it, I had created it as flat and not "FLAT". So it appears to be case sensitive.

Now to see how to apply that tag to all of my content. :) Thanks for chiming in peterpannimmerland!
