### ISSUE TITLE
Not Starting

### ISSUE THREAD

**Issue by dotslashsuperstar** [Tweeticoats/stash-vr-companion#10]
Any idea why my docker setup isn't working? I updated today and its failing. Log below...

*** Starting uWSGI 2.0.20 (64bit) on [Thu Dec  1 10:52:53 2022] ***

compiled with version: 8.3.0 on 01 December 2022 06:13:19

os: Linux-5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02)

nodename: 56baf5a952e1

machine: x86_64

clock source: unix

pcre jit disabled

detected number of CPU cores: 4

current working directory: /app

detected binary path: /usr/local/bin/uwsgi

uWSGI running as root, you can use --uid/--gid/--chroot options

*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 

*** WARNING: you are running uWSGI without its master process manager ***

your memory page size is 4096 bytes

detected max file descriptor number: 1048576

lock engine: pthread robust mutexes

thunder lock: disabled (you can enable it with --thunder-lock)

uWSGI http bound on :5000 fd 4

spawned uWSGI http 1 (pid: 7)

uwsgi socket 0 bound to TCP address 127.0.0.1:35255 (port auto-assigned) fd 3

uWSGI running as root, you can use --uid/--gid/--chroot options

*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 

Python version: 3.8.15 (default, Nov 15 2022, 22:19:38)  [GCC 8.3.0]

Python main interpreter initialized at 0x55fd0a3a8860

uWSGI running as root, you can use --uid/--gid/--chroot options

*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 

python threads support enabled

your server socket listen backlog is limited to 100 connections

your mercy for graceful operations on workers is 60 seconds

mapped 72920 bytes (71 KB) for 1 cores

*** Operational MODE: single process ***

Loading config from stash: {"filters": [{"name": "Recent", "type": "BUILTIN", "filter_name": "default", "sort_name": "date", "enabled": false}, {"name": "VR", "type": "BUILTIN", "filter_name": "3d", "sort_name": "date", "enabled": true}, {"name": "2D", "type": "BUILTIN", "filter_name": "2d", "sort_name": "date", "enabled": true}, {"name": "5star", "type": "BUILTIN", "filter_name": "star", "sort_name": "date", "enabled": true}, {"name": "Random", "type": "BUILTIN", "filter_name": "random", "sort_name": "random", "enabled": true}, {"name": "Interactive", "type": "BUILTIN", "filter_name": "interactive", "sort_name": "date", "enabled": true}, {"name": "Markers", "type": "BUILTIN", "filter_name": "markers", "sort_name": "date", "enabled": false}]}

final config:{'config_studio': 222, 'filters': [{'name': 'Recent', 'type': 'BUILTIN', 'filter_name': 'default', 'sort_name': 'date', 'enabled': False}, {'name': 'VR', 'type': 'BUILTIN', 'filter_name': '3d', 'sort_name': 'date', 'enabled': True}, {'name': '2D', 'type': 'BUILTIN', 'filter_name': '2d', 'sort_name': 'date', 'enabled': True}, {'name': '5star', 'type': 'BUILTIN', 'filter_name': 'star', 'sort_name': 'date', 'enabled': True}, {'name': 'Random', 'type': 'BUILTIN', 'filter_name': 'random', 'sort_name': 'random', 'enabled': True}, {'name': 'Interactive', 'type': 'BUILTIN', 'filter_name': 'interactive', 'sort_name': 'date', 'enabled': True}, {'name': 'Markers', 'type': 'BUILTIN', 'filter_name': 'markers', 'sort_name': 'date', 'enabled': False}]}

Cache currently contains 0

refreshing cache

Fetching 100 scenes

Fetching 200 scenes

Fetching 300 scenes

Fetching 400 scenes

Fetching 500 scenes

Fetching 600 scenes

Fetching 700 scenes

Fetching 800 scenes

Fetching 900 scenes

Fetching 1000 scenes

Fetching 1100 scenes

Fetching 1200 scenes

Cache currently contains  1165  scenes, checking image cache

fetching image: 2333

Traceback (most recent call last):

  File "app.py", line 2214, in <module>

    refreshCache()

  File "app.py", line 1790, in refreshCache

    with Image.open(f) as im:

  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 3135, in open

    fp.seek(0)

ValueError: seek of closed file

unable to load app 0 (mountpoint='') (callable not found or import error)

*** no app loaded. going in full dynamic mode ***

uWSGI running as root, you can use --uid/--gid/--chroot options

*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 

*** uWSGI is running in multiple interpreter mode ***

spawned uWSGI worker 1 (and the only) (pid: 1, cores: 1)

--- no python application found, check your startup logs for errors ---

[pid: 1|app: -1|req: -1/1] 10.1.1.112 () {38 vars in 1329 bytes} [Thu Dec  1 10:56:47 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)

**Comment by slabking** [comment]
Hey, did you ever figure this out? I'm getting similar errors. I was successfully running the Docker image on Ubuntu, but now that I'm trying to start it on Unraid, I'm seeing almost the same output.

**Comment by slabking** [comment]
Okay, I found the problem. For me, I had migrated Docker hosts, and the IP address of my Stash instance had changed. I had missed the `API_URL` environment variable needed to be updated (then I rebuilt the container). Pretty dumb, but I'm glad it was an easy fix!
