### ISSUE TITLE
Tagging scenes as VR

### ISSUE THREAD

**Issue by slabking** [Tweeticoats/stash-vr-companion#4]
Thanks again for this! I think I've mostly gotten things working, but I'm having trouble tagging VR scenes in Stash. Could I ask for some help?

From the README, every VR scene needs to have `export_deovr` applied, correct? Since I keep my VR files in their own folder, and I'm using Docker, I've managed this by adding it to my volume's path: `/path/to/vr/files:/vr_files/export_deovr`. Stash's autotagger picks up on `export_deovr` being in the path and adds the tag automatically. :)

For the other tags, I'm having some trouble figuring out how to apply them. It looks like I need one of these:

```
FLAT
DOME
SPHERE
FISHEYE
MKX200
```

And one of these:

```
SBS
TB
```

I can pretty easily figure out if a scene is `SBS` or `TB` (it's even easier that scenes default to `SBS` even without the tag), but the first list has me stumped. Is there a good way to tell the difference between them, just by watching the video? It'd be great if the README contained examples of each, or linked to an explanation somewhere else, but I totally understand if that's outside of the scope of this project. I haven't been able to find anything in my own searching.

**Comment by jhs** [comment]
Cheeky reply two years later!

I've been reading the code a bit and I believe your description of the logic is correct. I have hopefully [clarified how tags work](https://github.com/jhs/stash-vr-companion/blob/master/README.md) in the README in my form.

About detecting the projection, I think it is easy by eye but may require some work to do automatically:

- Fisheye, MKX200, 190, etc. have large circles of content with unused, usually black backgrounds
- For most videos, if it is side-by-side 3D but not fisheye, it is almost always `DOME`, in my experience

I believe the other tags are "VR" but not 3D, which are less common.

**Comment by jhs** [comment]
@Tweeticoats I propose you close this ticket since @slabking has an answer to his question.

**Comment by slabking** [comment]
Thanks! This definitely helps. I've learned a bit since opening this issue, but I appreciate you updating the README to provide more clarification!
